title: Sanghyun Son
logo: #https://cv.snu.ac.kr/member/images/shson.jpg
description: #<p><b>Ph. D candidate</b><br>Department of ECE, Seoul National University (SNU), Seoul, Korea</p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
